apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  root-password: cm9vdDEyMyE=  # echo -n 'root123!' | base64
  user-password: YXBwdXNlcjEyMyE=  # echo -n 'appuser123!' | base64