apiVersion: v1
kind: Service
metadata:
  name: grafana-proxy  # 简单的名称，符合 DNS-1035
  namespace: default   # 与 Ingress 相同的 namespace
spec:
  type: ExternalName
  externalName: prometheus-grafana.monitoring.svc.cluster.local
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-proxy  # 简单的名称，符合 DNS-1035
  namespace: default   # 与 Ingress 相同的 namespace
spec:
  type: ExternalName
  externalName: prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sprint-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

spec:
  ingressClassName: nginx
  rules:
  - host: spring.wilson.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sprint-service
            port:
              number: 8080
  - host: grafana.wilson.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-proxy
            port:
              number: 80
  - host: prometheus.wilson.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-proxy
            port:
              number: 80
      