apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.secret.rootPassword }}
  mysql-root-password: {{ .Values.secret.rootPassword | b64enc | quote }}
  {{- else }}
  mysql-root-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secret.username }}
  mysql-username: {{ .Values.secret.username | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.secret.password }}
  mysql-password: {{ .Values.secret.password | b64enc | quote }}
  {{- else }}
  mysql-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}